baseURL = "/"
title = "@qrui"

disableKinds = ["taxonomy"]
enableEmoji = true
enableRobotsTXT = true
hasCJKLanguage = true
ignoreErrors = ["error-disable-taxonomy"]
theme = "fuji"

## Change this two to switch between different language
defaultContentLanguage = "en" # For HTML page, now support: en, zh-hans, zh-hant, ja, nl
languageCode = "en" # For RSS, view https://www.rssboard.org/rss-language-codes

paginate = 20 
summaryLength = 30 # Custom summary length, add <!--more--> in post file to custom split point

googleAnalytics = "UA-80926729-1" # Set your Google Analytics UA here

[outputFormats]
[outputFormats.SearchIndex]
isPlainText = true
mediaType = "application/json"
notAlternative = true
path = "/search/"

[outputs]
home = ["HTML", "RSS", "SearchIndex"]

[permalinks]
post = "/:section/:filename/" # Custom post links, e.g. "/:year/:month/:title/"

[params]
author = "Qi≈´ Ru√¨" # You can also set author in post front matter individually
subTitle = "Half data viz tinkering, half chaos." 

# Use CloudFlare Workers to accelerate the Google Analytics
# If you are using this please comment the googleAnalytics above
# Check https://github.com/SukkaW/cloudflare-workers-async-google-analytics for more details
# googleAnalyticsTid = "UA-000000000-0"
# googleAnalyticsRoute = "https://*.*.workers.dev/"

# Google AdSense
# The AdSense code will be inserted between the head tags of your site.
# googleAdsense = "0000000000000000"

# Word counter and read time indicator in post metadata
showReadTime = false
showWordCounter = true

# License at the end of each post
showLicense = true
showToc = false

# Open Graph & Twitter Card variables
# You can also set description and images in post front matter individually
description = "A blog of Qi≈´ Ru√¨" 
og = "/img/open_graph.png" # This will use the image called og.png in static/img folder

# Posts shown in homepage
mainSections = ["post"]
nopieSections = ["nopie"]

# Bangumi image chart id
# bgmImageChart = "000000"

# License
license = "CC BY-NC-SA 4.0"
licenseLink = "http://creativecommons.org/licenses/by-nc-sa/4.0/"

# Comments
# utterances, see: https://utteranc.es/
# utterancesRepo = "*/*"
# utterancesIssueTerm = "pathname"

# Disqus, see: https://disqus.com/admin/install/platforms/universalcode/
# disqusShortname = ""
# Also use DisqusJS for accessing from Mainland China, see: https://github.com/SukkaW/DisqusJS
# If you want to set multiple api key, see theme's README for more details
# disqusJSApi = "https://*********/"
# disqusJSApikey = "**********"

# custom lazyload placeholder
# 16:9
lazyPlaceholder = "/assets/lazyload/dsrca_loading_480x270.svg"
# 32:9
lazyPlaceholderRow = "/assets/lazyload/dsrca_loading_960x270.svg"
# 8:9
lazyPlaceholderCol = "/assets/lazyload/dsrca_loading_480x540.svg"

# Use Hugo Pipes in Hugo Extended Version to compile SCSS
useHugoPipes = true

# Let images display in full brightness under dark mode
disableDarkImage = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true # Enable user to embed HTML snippets in Markdown content
[markup.highlight]
codeFences = false # Disable Hugo's code highlighter

[markup.tableOfContents]
endLevel = 3
startLevel = 2

[taxonomies]
tag = "tags"

[menu]
[[menu.nav]]
name = "Home"
url = "/"
weight = 1
[[menu.nav]]
name = "No Pie Weekly"
url = "/nopie/"
weight = 2
[[menu.nav]]
name = "Now"
url = "/now/"
weight = 3
[[menu.nav]]
name = "Archives"
url = "/archives/"
weight = 4
[[menu.nav]]
name = "Search"
url = "/search/"
weight = 5
[[menu.nav]]
name = "RSS"
url = "/index.xml"
weight = 6

[[menu.link]]
name = "üì∑ Gallery"
url = "https://airavo.netlify.app"
weight = 1
[[menu.link]]
name = "üê± GitHub"
url = "https://github.com/rexarski"
weight = 2
[[menu.link]]
name = "üìñ Goodreads"
url = "https://www.goodreads.com/user/show/66423413-ru"
weight = 3
[[menu.link]]
name = "üñå Hypothes.is"
url = "https://hypothes.is/users/rexarski"
weight = 4
[[menu.link]]
name = "üóù Keybase"
url = "https://keybase.io/rexarski/chat"
weight = 5
[[menu.link]]
name = "üì• Newsletter"
url = "https://world.hey.com/qrui"
weight = 6
[[menu.link]]
name = "üìå Pinboard"
url = "https://pinboard.in/u:rexarski"
weight = 7
[[menu.link]]
name = "üì£ Telegram"
url = "https://t.me/itsnopie"
weight = 8
[[menu.link]]
name = "üê¶ Twitter"
url = "https://twitter.com/rexarski"
weight = 9
[[menu.link]]
name = "üå± Ë±ÜÁì£"
url = "https://www.douban.com/people/rexarski/"
weight = 10
