# DO NOT REMOVE THIS

copyright = "© {year} Qiū Ruì"
theme = "hugo-theme-codex"
title = "qrui"

# Override these settings with your own
baseURL = "/"
languageCode = "en-us"

# Only use this with i18n
# DefaultContentLanguage = "en-us"

# Add your Disqus shortname here.
disqusShortname = "rexarski"

# Add your Google Analytics identifier: UA-XXXXXXXX-X
# googleAnalytics = ""

# Optional params
[params]
# Follow the Hugo date/time format reference here:
# https://gohugo.io/functions/format/#gos-layout-string
dateFormat = "Jan 2 2006"

# Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
email = "mailto:qiurui416@gmail.com"
github = "https://github.com/rexarski"
twitter = "https://twitter.com/rexarski"
# facebook = "https://facebook.com/<your handle>"
# gitlab = "https://gitlab.com/<your handle>"
# instagram = "https://instagram.com/<your handle>"
# linkedin = "<link to your profile>"
# youtube = "https://www.youtube.com/channel/<your channel>"
blog = "https://interetro.rbind.io"

# Titles for your icons (shown as tooltips), and also their display order.
# Currently, these icons are supported:
#   "Twitter", "GitHub", "Email", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
iconTitles = ["Twitter", "GitHub", "Email", "Blog"]

# Metadata for Twitter cards, defaults to params.twitter
twitterAuthor = "@rexarski"
twitterSite = "@rexarski"

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
[markup.highlight]
codeFences = false
guessSyntax = false
noClasses = true
# style = "monokai" # somehow it cannot override the scss/partials/_github-syntax-highlight.scss
tabWidth = 2

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.extensions]
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
[markup.goldmark.renderer]
unsafe = true

# Controls the navigation
[menu]
[[menu.main]]
identifier = "blog"
name = "blog"
title = "blog"
url = "/blog"
weight = 1

[[menu.main]]
identifier = "now"
name = "now"
title = "now"
url = "/now"
weight = 2

[[menu.main]]
identifier = "uses"
name = "uses"
title = "uses"
url = "/uses"
weight = 3

[[menu.main]]
identifier = "rss"
name = "rss"
title = "rss"
url = "/index.xml"
weight = 4

[[menu.main]]
identifier = "home"
name = "home"
title = "home"
url = "/"
weight = 5
